[tool.isort]
profile = "black"

[tool.black]
line-length = 79
target-version = ['py311']

[tool.pytest.ini_options]
pythonpath = "."
addopts = "-vv -p no:cacheprovider --disable-warnings"
testpaths = ["tests/"]
python_files = ["test_*.py"]
asyncio_mode= "auto"
