"""001

Revision ID: b9c55a2695f4
Revises:
Create Date: 2023-03-26 12:42:45.688031

"""
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision = "b9c55a2695f4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth",
        sa.Column("user_type", sa.Integer(), nullable=True),
        sa.Column(
            "email",
            sqlmodel.sql.sqltypes.AutoString(length=254),
            nullable=False,
        ),
        sa.Column(
            "password",
            sqlmodel.sql.sqltypes.AutoString(length=64),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_auth_email"), "auth", ["email"], unique=True)
    op.create_table(
        "institution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tutor",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "parent",
        sa.Column(
            "name",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column(
            "surname",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column(
            "patronic",
            sqlmodel.sql.sqltypes.AutoString(length=128),
            nullable=True,
        ),
        sa.Column("born", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("auth_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["auth_id"],
            ["auth.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("parent")
    op.drop_table("tutor")
    op.drop_table("institution")
    op.drop_index(op.f("ix_auth_email"), table_name="auth")
    op.drop_table("auth")
    # ### end Alembic commands ###
